{%set name = "Routes" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "b6346459a15f0cbab01a45a90c3d25caf980d4733d628b4cc1952b865125d053"

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip

  run:
    - python
    - six
    - repoze.lru >=0.3

test:
  imports:
    - routes
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://routes.readthedocs.io/
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: Routing Recognition and Generation Tools
  description: |
    Routes is a Python re-implementation of the Rails routes system for
    mapping URL's to Controllers/Actions and generating URL's. Routes makes
    it easy to create pretty and concise URL's that are RESTful with little
    effort.
  dev_url: https://github.com/bbangert/routes
  doc_url: https://routes.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
