# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "U0aVSKRnfEzXiHMew5ssxQ06jNbyX2XANEdUA/V2alW4Sz4O98gsnow3JlSGXLR1fUUqxCJ4AwliD7PkCPHwswRMHZ7RaLMFlnuYcAtX8pH2hSWtxxbifUnMdb6/T1ByYCoQlTZC1LNdHEkrnmwAr9FA2mk84fgnOKsbXAIJl7yFPmyFwhj56EIQo5MMkI6NMDsZJW74FJQb5tZxO+S6Yv/i8NE5sja4Q1nyJr0lEek7isZcqRjUA4HFSAGJG8vCZHYM33JB8nzm9NyjB0526ZRR3hoxmuysSQMbSqS1GK/6MJLzHAvGFwvY+WmqarL3wt/HvLG8LTfU/Ay3yVl74QUQgJEoFOX0nyHE1bZgwfSnJcwk5PcUVXEFBXniCCkq0976u/twF32sgI+jDJklka3tbeYI4YaO6EfUMTMajAHPDn467TC63Hnrc38DWDCAK9VfY/cql4FRByRhCvf5tmFOmOgPoy1C/5RyoKiTWN5/vjW5/164/b0Nu3YFXNEYSRb+ds9iv0LqPGDdjjZm2gT4EKQoIWfUosL4K4Sb0IXavSH9svdFs5NyutU7badtnIIryFdLi7CFdRMYXNFy1PbOM47kq6qrSX3PTjOda7uIqdYCBoF2tGg/hInRF7RNOUueB+j0XHCQaSmuKhk0mVbAXDgsl4zUG6AZ4hmyXnA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
