# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "nvBZwuGyBc9TyYmS55hLU2iqHo8bZmzC9cCQqy0EhvY3RyNWXp5k60p1CUpagY/wsL8fohIGLN9J24aqs1iCuu/e4sqBhmPkypW8aZIifMjI3sFvk7+9aLZO5bFqxB3ZWyAsq3WddkX5PAxu7VnL9el38mbn1LLRisdmOvsTUt4Ds33syX+NffLXWCwr01DpGp7HjlmyW/3NY9pywTks/iRvr2tBu/8jW0+jfM54/wwHJcPJuYhIriBPMFrjHATD5fdizw5zPoXRrtDZurFDwO85eGoTpDt+b400cIvXHn3XrCjNSPwr/e+w/TypQAH/e1AZBGnlblSrnxUKTP2p3ybOUJ9LXOC5WiPAbD09yT1ytiI91FHosrXQ4ms+ENkMQeQ2ZUbA4UseoutzeoSb+anACCQXlNP+S3zYhMhSpOC7ocnFKl7qFiKbraRTymIdO5o24LQZaO1trfaC/tKWdhTIuTb0kBOq/bfcx8EQXLL7Q59Mpec8GOuRDC3gme3bz/4V9fCbW/hrEv+NIo2kv9F8i7R5RMSomsmUnJtMFLTVJC3uPSi/+l0gzFoSjLpvk/Mrstouqw2QZAmhEynrg3ZX7BxEwdMVffRJJLgixzxzxMKRXKUsojMBioUxv3zuCmpsbUkxdExkaiHwb6edaau87J9GDQ4tld3RJ/qZaVI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
