travis:
  secure:
    BINSTAR_TOKEN: U0aVSKRnfEzXiHMew5ssxQ06jNbyX2XANEdUA/V2alW4Sz4O98gsnow3JlSGXLR1fUUqxCJ4AwliD7PkCPHwswRMHZ7RaLMFlnuYcAtX8pH2hSWtxxbifUnMdb6/T1ByYCoQlTZC1LNdHEkrnmwAr9FA2mk84fgnOKsbXAIJl7yFPmyFwhj56EIQo5MMkI6NMDsZJW74FJQb5tZxO+S6Yv/i8NE5sja4Q1nyJr0lEek7isZcqRjUA4HFSAGJG8vCZHYM33JB8nzm9NyjB0526ZRR3hoxmuysSQMbSqS1GK/6MJLzHAvGFwvY+WmqarL3wt/HvLG8LTfU/Ay3yVl74QUQgJEoFOX0nyHE1bZgwfSnJcwk5PcUVXEFBXniCCkq0976u/twF32sgI+jDJklka3tbeYI4YaO6EfUMTMajAHPDn467TC63Hnrc38DWDCAK9VfY/cql4FRByRhCvf5tmFOmOgPoy1C/5RyoKiTWN5/vjW5/164/b0Nu3YFXNEYSRb+ds9iv0LqPGDdjjZm2gT4EKQoIWfUosL4K4Sb0IXavSH9svdFs5NyutU7badtnIIryFdLi7CFdRMYXNFy1PbOM47kq6qrSX3PTjOda7uIqdYCBoF2tGg/hInRF7RNOUueB+j0XHCQaSmuKhk0mVbAXDgsl4zUG6AZ4hmyXnA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
