travis:
  secure:
    BINSTAR_TOKEN: nvBZwuGyBc9TyYmS55hLU2iqHo8bZmzC9cCQqy0EhvY3RyNWXp5k60p1CUpagY/wsL8fohIGLN9J24aqs1iCuu/e4sqBhmPkypW8aZIifMjI3sFvk7+9aLZO5bFqxB3ZWyAsq3WddkX5PAxu7VnL9el38mbn1LLRisdmOvsTUt4Ds33syX+NffLXWCwr01DpGp7HjlmyW/3NY9pywTks/iRvr2tBu/8jW0+jfM54/wwHJcPJuYhIriBPMFrjHATD5fdizw5zPoXRrtDZurFDwO85eGoTpDt+b400cIvXHn3XrCjNSPwr/e+w/TypQAH/e1AZBGnlblSrnxUKTP2p3ybOUJ9LXOC5WiPAbD09yT1ytiI91FHosrXQ4ms+ENkMQeQ2ZUbA4UseoutzeoSb+anACCQXlNP+S3zYhMhSpOC7ocnFKl7qFiKbraRTymIdO5o24LQZaO1trfaC/tKWdhTIuTb0kBOq/bfcx8EQXLL7Q59Mpec8GOuRDC3gme3bz/4V9fCbW/hrEv+NIo2kv9F8i7R5RMSomsmUnJtMFLTVJC3uPSi/+l0gzFoSjLpvk/Mrstouqw2QZAmhEynrg3ZX7BxEwdMVffRJJLgixzxzxMKRXKUsojMBioUxv3zuCmpsbUkxdExkaiHwb6edaau87J9GDQ4tld3RJ/qZaVI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
